# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Brendon
tagline:          'Writes Code, Plays Games, Gets Distracted'
description:      'Writes Code, Plays Games, Gets Distracted'
url:              http://brendon1555.com
baseurl:          /

author:
  name:           'Brendon Lees'
  url:            https://twitter.com/brendon1555

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/brendon1555
twitter:           https://twitter.com/brendon1555


gems:             [jekyll-paginate, jekyll-gist]